#!/bin/bash

# Music Folder
# m="$m" # already assigned

if [ "$1" != "" ]; then
  # If not renaming, then make it the same
  if [ "$2" ]; then
    target="$2"
  else
    target="$1"
  fi

  # Check to see if $1 is a symlink
  if [ -L "$1" ]; then
    echo "Hmm, it looks like '$1' is already a symlink"
    exit
  fi

  if [ -e "$m"/"$target" ]; then
    echo "Hmm, looks like '$target' already exists in $m"
    echo "Moving to ~/dupe/"
    mv "$1" ~/dupe/"$target"
    exit
  fi

  mv "$1" "$m"/"$target"
  ln -s "$m"/"$target" "$1"
else
  echo 'Missing argument: requires a source name'
fi
